- name : Configure Docker on EC2 Instances
  hosts : 172.31.45.42   #installing on prometheus sever 
  become: true
  connection : ssh
  tasks : 
  - name: updating apt
    command : sudo apt-get update

  - name : Install Docker
    command : sudo apt-get install -y docker.io

  - name : Start Docker Service
    command : sudo systemctl start docker

  - name: Deploy Docker Container
    command: docker run -itd -p 8081:8081 pradip698/banking-finance-project:v1
